version: "3"

services:
  sample:
    container_name: ciclismurban-map
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
