export enum RegisterTypes {
  REQUEST = "USER__REGISTER__REQUEST",
  SUCCESS = "USER__REGISTER__SUCCESS",
  FAILURE = "USER__REGISTER__FAILURE",
}

export enum LoginTypes {
  REQUEST = "USER__LOGIN__REQUEST",
  SUCCESS = "USER__LOGIN__SUCCESS",
  FAILURE = "USER__LOGIN__FAILURE",
}

export enum LoginByTokenTypes {
  REQUEST = "USER__LOGIN_BY_TOKEN__REQUEST",
  SUCCESS = "USER__LOGIN_BY_TOKEN__SUCCESS",
  FAILURE = "USER__LOGIN_BY_TOKEN__FAILURE",
}

export const LogoutType = "USER__LOGOUT"
