export enum MeGetTypes {
  REQUEST = "ME__GET__REQUEST",
  SUCCESS = "ME__GET__SUCCESS",
  FAILURE = "ME__GET__FAILURE",
}

export enum MeUpdateProfileTypes {
  REQUEST = "ME__UPDATE__PROFILE__REQUEST",
  SUCCESS = "ME__UPDATE__PROFILE__SUCCESS",
  FAILURE = "ME__UPDATE__PROFILE__FAILURE",
}
