export enum FiltersTypes {
  TOGGLE = "LOCATIONS__FILTERS__TOGGLE",
  RESET = "LOCATIONS__FILTERS__RESET",
}

export enum CurrentTypes {
  POLLING__START = "LOCATIONS__CURRENT__POLLING__START",
  POLLING__STOP = "LOCATIONS__CURRENT__POLLING__STOP",
  GET__REQUEST = "LOCATIONS__CURRENT__GET__REQUEST",
  GET__SUCCESS = "LOCATIONS__CURRENT__GET__SUCCESS",
  GET__FAILURE = "LOCATIONS__CURRENT__GET__FAILURE",
}

export enum ParkingsTypes {
  GET__REQUEST = "LOCATIONS__PARKINGS__GET__REQUEST",
  GET__SUCCESS = "LOCATIONS__PARKINGS__GET__SUCCESS",
  GET__FAILURE = "LOCATIONS__PARKINGS__GET__FAILURE",
}

export enum ServicesTypes {
  GET__REQUEST = "LOCATIONS__SERVICES__GET__REQUEST",
  GET__SUCCESS = "LOCATIONS__SERVICES__GET__SUCCESS",
  GET__FAILURE = "LOCATIONS__SERVICES__GET__FAILURE",
}

export enum ShopsTypes {
  GET__REQUEST = "LOCATIONS__SHOPS__GET__REQUEST",
  GET__SUCCESS = "LOCATIONS__SHOPS__GET__SUCCESS",
  GET__FAILURE = "LOCATIONS__SHOPS__GET__FAILURE",
}

export enum SelectedTypes {
  GET__REQUEST = "LOCATION__SELECTED__GET__REQUEST",
  GET__SUCCESS = "LOCATION__SELECTED__GET__SUCCESS",
  GET__FAILURE = "LOCATION__SELECTED__GET__FAILURE",
  CLEAR = "LOCATION__SELECTED__CLEAR",
}

export const ACCEPTED_ENTITIES = ["parkings", "services", "shops"] as const
export type TAcceptedEntity = typeof ACCEPTED_ENTITIES[number]
