export enum Get {
  REQUEST = "LOCATIONS__EVENTS__GET__REQUEST",
  SUCCESS = "LOCATIONS__EVENTS__GET__SUCCESS",
  FAILURE = "LOCATIONS__EVENTS__GET__FAILURE",
}

export enum Create {
  REQUEST = "LOCATIONS__EVENTS__CREATE__REQUEST",
  SUCCESS = "LOCATIONS__EVENTS__CREATE__SUCCESS",
  FAILURE = "LOCATIONS__EVENTS__CREATE__FAILURE",
}

export enum Update {
  REQUEST = "LOCATIONS__EVENTS__UPDATE__REQUEST",
  SUCCESS = "LOCATIONS__EVENTS__UPDATE__SUCCESS",
  FAILURE = "LOCATIONS__EVENTS__UPDATE__FAILURE",
}

export enum Delete {
  REQUEST = "LOCATIONS__EVENTS__DELETE__REQUEST",
  SUCCESS = "LOCATIONS__EVENTS__DELETE__SUCCESS",
  FAILURE = "LOCATIONS__EVENTS__DELETE__FAILURE",
}
