export enum Get {
  REQUEST = "LOCATIONS__SERVICES__GET__REQUEST",
  SUCCESS = "LOCATIONS__SERVICES__GET__SUCCESS",
  FAILURE = "LOCATIONS__SERVICES__GET__FAILURE",
}

export enum Create {
  REQUEST = "LOCATIONS__SERVICES__CREATE__REQUEST",
  SUCCESS = "LOCATIONS__SERVICES__CREATE__SUCCESS",
  FAILURE = "LOCATIONS__SERVICES__CREATE__FAILURE",
}

export enum Update {
  REQUEST = "LOCATIONS__SERVICES__UPDATE__REQUEST",
  SUCCESS = "LOCATIONS__SERVICES__UPDATE__SUCCESS",
  FAILURE = "LOCATIONS__SERVICES__UPDATE__FAILURE",
}

export enum Delete {
  REQUEST = "LOCATIONS__SERVICES__DELETE__REQUEST",
  SUCCESS = "LOCATIONS__SERVICES__DELETE__SUCCESS",
  FAILURE = "LOCATIONS__SERVICES__DELETE__FAILURE",
}
