export enum Get {
  REQUEST = "LOCATIONS__SHOPS__GET__REQUEST",
  SUCCESS = "LOCATIONS__SHOPS__GET__SUCCESS",
  FAILURE = "LOCATIONS__SHOPS__GET__FAILURE",
}

export enum Create {
  REQUEST = "LOCATIONS__SHOPS__CREATE__REQUEST",
  SUCCESS = "LOCATIONS__SHOPS__CREATE__SUCCESS",
  FAILURE = "LOCATIONS__SHOPS__CREATE__FAILURE",
}

export enum Update {
  REQUEST = "LOCATIONS__SHOPS__UPDATE__REQUEST",
  SUCCESS = "LOCATIONS__SHOPS__UPDATE__SUCCESS",
  FAILURE = "LOCATIONS__SHOPS__UPDATE__FAILURE",
}

export enum Delete {
  REQUEST = "LOCATIONS__SHOPS__DELETE__REQUEST",
  SUCCESS = "LOCATIONS__SHOPS__DELETE__SUCCESS",
  FAILURE = "LOCATIONS__SHOPS__DELETE__FAILURE",
}
