export enum Get {
  REQUEST = "LOCATIONS__PARKINGS__GET__REQUEST",
  SUCCESS = "LOCATIONS__PARKINGS__GET__SUCCESS",
  FAILURE = "LOCATIONS__PARKINGS__GET__FAILURE",
}

export enum Create {
  REQUEST = "LOCATIONS__PARKINGS__CREATE__REQUEST",
  SUCCESS = "LOCATIONS__PARKINGS__CREATE__SUCCESS",
  FAILURE = "LOCATIONS__PARKINGS__CREATE__FAILURE",
}

export enum Update {
  REQUEST = "LOCATIONS__PARKINGS__UPDATE__REQUEST",
  SUCCESS = "LOCATIONS__PARKINGS__UPDATE__SUCCESS",
  FAILURE = "LOCATIONS__PARKINGS__UPDATE__FAILURE",
}

export enum Delete {
  REQUEST = "LOCATIONS__PARKINGS__DELETE__REQUEST",
  SUCCESS = "LOCATIONS__PARKINGS__DELETE__SUCCESS",
  FAILURE = "LOCATIONS__PARKINGS__DELETE__FAILURE",
}
