export enum Get {
  REQUEST = "ME__USER__GET__REQUEST",
  SUCCESS = "ME__USER__GET__SUCCESS",
  FAILURE = "ME__USER__GET__FAILURE",
}

export enum UpdateProfile {
  REQUEST = "ME__USER__UPDATE__PROFILE__REQUEST",
  SUCCESS = "ME__USER__UPDATE__PROFILE__SUCCESS",
  FAILURE = "ME__USER__UPDATE__PROFILE__FAILURE",
}
